# Generated by Django 4.2.1 on 2023-05-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
