# Generated by Django 4.2.1 on 2023-05-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
