# Generated by Django 4.2.1 on 2023-05-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
